export type ServiceGalleryImage = {
  id: string;
  src: string;
  webpSrcSet: string;
  sizes: string;
  width: number;
  height: number;
  alt: string;
};

export const serviceGalleries: Partial<Record<string, ServiceGalleryImage[]>> = {
  "cotton-candy": [
    {
      id: "cotton-candy-image-01",
      src: "/images/service-galleries/cotton-candy/image-01.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-01-480.webp 480w, /images/service-galleries/cotton-candy/image-01-720.webp 720w, /images/service-galleries/cotton-candy/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Сахарная вата — фото 1",
    },
    {
      id: "cotton-candy-image-02",
      src: "/images/service-galleries/cotton-candy/image-02.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-02-480.webp 480w, /images/service-galleries/cotton-candy/image-02-720.webp 720w, /images/service-galleries/cotton-candy/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Сахарная вата — фото 2",
    },
    {
      id: "cotton-candy-image-03",
      src: "/images/service-galleries/cotton-candy/image-03.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-03-480.webp 480w, /images/service-galleries/cotton-candy/image-03-720.webp 720w, /images/service-galleries/cotton-candy/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1195,
      alt: "Сахарная вата — фото 3",
    },
    {
      id: "cotton-candy-image-04",
      src: "/images/service-galleries/cotton-candy/image-04.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-04-480.webp 480w, /images/service-galleries/cotton-candy/image-04-720.webp 720w, /images/service-galleries/cotton-candy/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 640,
      alt: "Сахарная вата — фото 4",
    },
  ],
  "popcorn": [
    {
      id: "popcorn-image-01",
      src: "/images/service-galleries/popcorn/image-01.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-01-480.webp 480w, /images/service-galleries/popcorn/image-01-720.webp 720w, /images/service-galleries/popcorn/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Попкорн — фото 1",
    },
    {
      id: "popcorn-image-02",
      src: "/images/service-galleries/popcorn/image-02.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-02-480.webp 480w, /images/service-galleries/popcorn/image-02-720.webp 720w, /images/service-galleries/popcorn/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Попкорн — фото 2",
    },
    {
      id: "popcorn-image-03",
      src: "/images/service-galleries/popcorn/image-03.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-03-480.webp 480w, /images/service-galleries/popcorn/image-03-720.webp 720w, /images/service-galleries/popcorn/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Попкорн — фото 3",
    },
  ],
  "cotton-candy-popcorn": [
    {
      id: "cotton-candy-popcorn-image-01",
      src: "/images/service-galleries/cotton-candy-popcorn/image-01.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-01-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-01-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Сахарная вата + попкорн — фото 1",
    },
    {
      id: "cotton-candy-popcorn-image-02",
      src: "/images/service-galleries/cotton-candy-popcorn/image-02.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-02-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-02-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Сахарная вата + попкорн — фото 2",
    },
    {
      id: "cotton-candy-popcorn-image-03",
      src: "/images/service-galleries/cotton-candy-popcorn/image-03.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-03-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-03-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1195,
      alt: "Сахарная вата + попкорн — фото 3",
    },
    {
      id: "cotton-candy-popcorn-image-04",
      src: "/images/service-galleries/cotton-candy-popcorn/image-04.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-04-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-04-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 640,
      alt: "Сахарная вата + попкорн — фото 4",
    },
    {
      id: "cotton-candy-popcorn-image-05",
      src: "/images/service-galleries/cotton-candy-popcorn/image-05.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-05-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-05-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Сахарная вата + попкорн — фото 5",
    },
    {
      id: "cotton-candy-popcorn-image-06",
      src: "/images/service-galleries/cotton-candy-popcorn/image-06.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-06-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-06-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Сахарная вата + попкорн — фото 6",
    },
    {
      id: "cotton-candy-popcorn-image-07",
      src: "/images/service-galleries/cotton-candy-popcorn/image-07.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-07-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-07-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-07-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Сахарная вата + попкорн — фото 7",
    },
  ],
  "caramel-apples": [
    {
      id: "caramel-apples-image-01",
      src: "/images/service-galleries/caramel-apples/image-01.jpg",
      webpSrcSet: "/images/service-galleries/caramel-apples/image-01-480.webp 480w, /images/service-galleries/caramel-apples/image-01-720.webp 720w, /images/service-galleries/caramel-apples/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Карамельные яблоки — фото 1",
    },
    {
      id: "caramel-apples-image-02",
      src: "/images/service-galleries/caramel-apples/image-02.jpg",
      webpSrcSet: "/images/service-galleries/caramel-apples/image-02-480.webp 480w, /images/service-galleries/caramel-apples/image-02-720.webp 720w, /images/service-galleries/caramel-apples/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Карамельные яблоки — фото 2",
    },
  ],
  "roll-ice-cream": [
    {
      id: "roll-ice-cream-image-01",
      src: "/images/service-galleries/roll-ice-cream/image-01.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-01-480.webp 480w, /images/service-galleries/roll-ice-cream/image-01-720.webp 720w, /images/service-galleries/roll-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 817,
      alt: "Мороженое (Ролл) — фото 1",
    },
    {
      id: "roll-ice-cream-image-02",
      src: "/images/service-galleries/roll-ice-cream/image-02.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-02-480.webp 480w, /images/service-galleries/roll-ice-cream/image-02-720.webp 720w, /images/service-galleries/roll-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 767,
      alt: "Мороженое (Ролл) — фото 2",
    },
    {
      id: "roll-ice-cream-image-03",
      src: "/images/service-galleries/roll-ice-cream/image-03.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-03-480.webp 480w, /images/service-galleries/roll-ice-cream/image-03-720.webp 720w, /images/service-galleries/roll-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Ролл) — фото 3",
    },
    {
      id: "roll-ice-cream-image-04",
      src: "/images/service-galleries/roll-ice-cream/image-04.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-04-480.webp 480w, /images/service-galleries/roll-ice-cream/image-04-720.webp 720w, /images/service-galleries/roll-ice-cream/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Ролл) — фото 4",
    },
  ],
  "scoop-ice-cream": [
    {
      id: "scoop-ice-cream-image-01",
      src: "/images/service-galleries/scoop-ice-cream/image-01.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-01-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-01-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Шариковое) — фото 1",
    },
    {
      id: "scoop-ice-cream-image-02",
      src: "/images/service-galleries/scoop-ice-cream/image-02.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-02-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-02-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Шариковое) — фото 2",
    },
    {
      id: "scoop-ice-cream-image-03",
      src: "/images/service-galleries/scoop-ice-cream/image-03.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-03-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-03-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Шариковое) — фото 3",
    },
    {
      id: "scoop-ice-cream-image-04",
      src: "/images/service-galleries/scoop-ice-cream/image-04.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-04-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-04-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Мороженое (Шариковое) — фото 4",
    },
  ],
  "nitro-ice-cream": [
    {
      id: "nitro-ice-cream-image-01",
      src: "/images/service-galleries/nitro-ice-cream/image-01.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-01-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-01-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Азотное) — фото 1",
    },
    {
      id: "nitro-ice-cream-image-02",
      src: "/images/service-galleries/nitro-ice-cream/image-02.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-02-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-02-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Азотное) — фото 2",
    },
    {
      id: "nitro-ice-cream-image-03",
      src: "/images/service-galleries/nitro-ice-cream/image-03.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-03-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-03-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Мороженое (Азотное) — фото 3",
    },
  ],
  "chocolate-fountain": [
    {
      id: "chocolate-fountain-image-01",
      src: "/images/service-galleries/chocolate-fountain/image-01.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-01-480.webp 480w, /images/service-galleries/chocolate-fountain/image-01-720.webp 720w, /images/service-galleries/chocolate-fountain/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Шоколадный фонтан — фото 1",
    },
    {
      id: "chocolate-fountain-image-02",
      src: "/images/service-galleries/chocolate-fountain/image-02.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-02-480.webp 480w, /images/service-galleries/chocolate-fountain/image-02-720.webp 720w, /images/service-galleries/chocolate-fountain/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Шоколадный фонтан — фото 2",
    },
    {
      id: "chocolate-fountain-image-03",
      src: "/images/service-galleries/chocolate-fountain/image-03.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-03-480.webp 480w, /images/service-galleries/chocolate-fountain/image-03-720.webp 720w, /images/service-galleries/chocolate-fountain/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Шоколадный фонтан — фото 3",
    },
    {
      id: "chocolate-fountain-image-04",
      src: "/images/service-galleries/chocolate-fountain/image-04.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-04-480.webp 480w, /images/service-galleries/chocolate-fountain/image-04-720.webp 720w, /images/service-galleries/chocolate-fountain/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Шоколадный фонтан — фото 4",
    },
  ],
  "belgian-waffles": [
    {
      id: "belgian-waffles-image-01",
      src: "/images/service-galleries/belgian-waffles/image-01.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-01-480.webp 480w, /images/service-galleries/belgian-waffles/image-01-720.webp 720w, /images/service-galleries/belgian-waffles/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Бельгийские вафли — фото 1",
    },
    {
      id: "belgian-waffles-image-02",
      src: "/images/service-galleries/belgian-waffles/image-02.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-02-480.webp 480w, /images/service-galleries/belgian-waffles/image-02-720.webp 720w, /images/service-galleries/belgian-waffles/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Бельгийские вафли — фото 2",
    },
    {
      id: "belgian-waffles-image-03",
      src: "/images/service-galleries/belgian-waffles/image-03.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-03-480.webp 480w, /images/service-galleries/belgian-waffles/image-03-720.webp 720w, /images/service-galleries/belgian-waffles/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Бельгийские вафли — фото 3",
    },
  ],
  "pancakes": [
    {
      id: "pancakes-image-01",
      src: "/images/service-galleries/pancakes/image-01.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-01-480.webp 480w, /images/service-galleries/pancakes/image-01-720.webp 720w, /images/service-galleries/pancakes/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Блины — фото 1",
    },
    {
      id: "pancakes-image-02",
      src: "/images/service-galleries/pancakes/image-02.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-02-480.webp 480w, /images/service-galleries/pancakes/image-02-720.webp 720w, /images/service-galleries/pancakes/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      alt: "Блины — фото 2",
    },
    {
      id: "pancakes-image-03",
      src: "/images/service-galleries/pancakes/image-03.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-03-480.webp 480w, /images/service-galleries/pancakes/image-03-720.webp 720w, /images/service-galleries/pancakes/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Блины — фото 3",
    },
  ],
  "champagne-pyramid": [
    {
      id: "champagne-pyramid-image-01",
      src: "/images/service-galleries/champagne-pyramid/image-01.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-01-480.webp 480w, /images/service-galleries/champagne-pyramid/image-01-720.webp 720w, /images/service-galleries/champagne-pyramid/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Пирамида из шампанского — фото 1",
    },
    {
      id: "champagne-pyramid-image-02",
      src: "/images/service-galleries/champagne-pyramid/image-02.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-02-480.webp 480w, /images/service-galleries/champagne-pyramid/image-02-720.webp 720w, /images/service-galleries/champagne-pyramid/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1173,
      alt: "Пирамида из шампанского — фото 2",
    },
    {
      id: "champagne-pyramid-image-03",
      src: "/images/service-galleries/champagne-pyramid/image-03.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-03-480.webp 480w, /images/service-galleries/champagne-pyramid/image-03-720.webp 720w, /images/service-galleries/champagne-pyramid/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1133,
      alt: "Пирамида из шампанского — фото 3",
    },
  ],
  "craft-lemonade": [
    {
      id: "craft-lemonade-image-01",
      src: "/images/service-galleries/craft-lemonade/image-01.jpg",
      webpSrcSet: "/images/service-galleries/craft-lemonade/image-01-480.webp 480w, /images/service-galleries/craft-lemonade/image-01-720.webp 720w, /images/service-galleries/craft-lemonade/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Крафтовый лимонад — фото 1",
    },
  ],
  "bubble-tea": [
    {
      id: "bubble-tea-image-01",
      src: "/images/service-galleries/bubble-tea/image-01.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-01-480.webp 480w, /images/service-galleries/bubble-tea/image-01-720.webp 720w, /images/service-galleries/bubble-tea/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Бабл ти — фото 1",
    },
    {
      id: "bubble-tea-image-02",
      src: "/images/service-galleries/bubble-tea/image-02.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-02-480.webp 480w, /images/service-galleries/bubble-tea/image-02-720.webp 720w, /images/service-galleries/bubble-tea/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Бабл ти — фото 2",
    },
    {
      id: "bubble-tea-image-03",
      src: "/images/service-galleries/bubble-tea/image-03.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-03-480.webp 480w, /images/service-galleries/bubble-tea/image-03-720.webp 720w, /images/service-galleries/bubble-tea/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      alt: "Бабл ти — фото 3",
    },
  ],
};
