export type ServiceGalleryImage = {
  id: string;
  src: string;
  originalSrc: string;
  webpSrcSet: string;
  sizes: string;
  width: number;
  height: number;
  originalWidth: number;
  originalHeight: number;
  alt: string;
};

export const serviceGalleries: Partial<Record<string, ServiceGalleryImage[]>> = {
  "cotton-candy": [
    {
      id: "cotton-candy-image-01",
      src: "/images/service-galleries/cotton-candy/image-01.png",
      originalSrc: "/images/service-galleries/cotton-candy/image-01-original.png",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-01-480.webp 480w, /images/service-galleries/cotton-candy/image-01-720.webp 720w, /images/service-galleries/cotton-candy/image-01-868.webp 868w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 868,
      height: 985,
      originalWidth: 868,
      originalHeight: 985,
      alt: "Сахарная вата — фото 1",
    },
    {
      id: "cotton-candy-image-02",
      src: "/images/service-galleries/cotton-candy/image-02.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-02-480.webp 480w, /images/service-galleries/cotton-candy/image-02-720.webp 720w, /images/service-galleries/cotton-candy/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Сахарная вата — фото 2",
    },
    {
      id: "cotton-candy-image-03",
      src: "/images/service-galleries/cotton-candy/image-03.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-03-480.webp 480w, /images/service-galleries/cotton-candy/image-03-720.webp 720w, /images/service-galleries/cotton-candy/image-03-919.webp 919w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 919,
      height: 1228,
      originalWidth: 919,
      originalHeight: 1228,
      alt: "Сахарная вата — фото 3",
    },
    {
      id: "cotton-candy-image-04",
      src: "/images/service-galleries/cotton-candy/image-04.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-04-480.webp 480w, /images/service-galleries/cotton-candy/image-04-720.webp 720w, /images/service-galleries/cotton-candy/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Сахарная вата — фото 4",
    },
    {
      id: "cotton-candy-image-05",
      src: "/images/service-galleries/cotton-candy/image-05.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-05-480.webp 480w, /images/service-galleries/cotton-candy/image-05-720.webp 720w, /images/service-galleries/cotton-candy/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Сахарная вата — фото 5",
    },
    {
      id: "cotton-candy-image-06",
      src: "/images/service-galleries/cotton-candy/image-06.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-06-480.webp 480w, /images/service-galleries/cotton-candy/image-06-720.webp 720w, /images/service-galleries/cotton-candy/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Сахарная вата — фото 6",
    },
    {
      id: "cotton-candy-image-07",
      src: "/images/service-galleries/cotton-candy/image-07.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-07-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-07-480.webp 480w, /images/service-galleries/cotton-candy/image-07-720.webp 720w, /images/service-galleries/cotton-candy/image-07-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 640,
      originalWidth: 1013,
      originalHeight: 675,
      alt: "Сахарная вата — фото 7",
    },
  ],
  "popcorn": [
    {
      id: "popcorn-image-01",
      src: "/images/service-galleries/popcorn/image-01.jpg",
      originalSrc: "/images/service-galleries/popcorn/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-01-480.webp 480w, /images/service-galleries/popcorn/image-01-720.webp 720w, /images/service-galleries/popcorn/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Попкорн — фото 1",
    },
    {
      id: "popcorn-image-02",
      src: "/images/service-galleries/popcorn/image-02.jpg",
      originalSrc: "/images/service-galleries/popcorn/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-02-480.webp 480w, /images/service-galleries/popcorn/image-02-720.webp 720w, /images/service-galleries/popcorn/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Попкорн — фото 2",
    },
    {
      id: "popcorn-image-03",
      src: "/images/service-galleries/popcorn/image-03.jpg",
      originalSrc: "/images/service-galleries/popcorn/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-03-480.webp 480w, /images/service-galleries/popcorn/image-03-720.webp 720w, /images/service-galleries/popcorn/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Попкорн — фото 3",
    },
  ],
  "cotton-candy-popcorn": [
    {
      id: "cotton-candy-popcorn-image-01",
      src: "/images/service-galleries/cotton-candy-popcorn/image-01.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-01-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-01-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Сахарная вата + попкорн — фото 1",
    },
    {
      id: "cotton-candy-popcorn-image-02",
      src: "/images/service-galleries/cotton-candy-popcorn/image-02.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-02-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-02-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Сахарная вата + попкорн — фото 2",
    },
    {
      id: "cotton-candy-popcorn-image-03",
      src: "/images/service-galleries/cotton-candy-popcorn/image-03.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-03-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-03-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Сахарная вата + попкорн — фото 3",
    },
    {
      id: "cotton-candy-popcorn-image-04",
      src: "/images/service-galleries/cotton-candy-popcorn/image-04.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-04-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-04-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Сахарная вата + попкорн — фото 4",
    },
    {
      id: "cotton-candy-popcorn-image-05",
      src: "/images/service-galleries/cotton-candy-popcorn/image-05.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-05-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-05-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Сахарная вата + попкорн — фото 5",
    },
  ],
  "caramel-apples": [
    {
      id: "caramel-apples-image-01",
      src: "/images/service-galleries/caramel-apples/image-01.jpg",
      originalSrc: "/images/service-galleries/caramel-apples/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/caramel-apples/image-01-480.webp 480w, /images/service-galleries/caramel-apples/image-01-720.webp 720w, /images/service-galleries/caramel-apples/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Карамельные яблоки — фото 1",
    },
    {
      id: "caramel-apples-image-02",
      src: "/images/service-galleries/caramel-apples/image-02.jpg",
      originalSrc: "/images/service-galleries/caramel-apples/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/caramel-apples/image-02-480.webp 480w, /images/service-galleries/caramel-apples/image-02-720.webp 720w, /images/service-galleries/caramel-apples/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Карамельные яблоки — фото 2",
    },
    {
      id: "caramel-apples-image-03",
      src: "/images/service-galleries/caramel-apples/image-03.jpg",
      originalSrc: "/images/service-galleries/caramel-apples/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/caramel-apples/image-03-480.webp 480w, /images/service-galleries/caramel-apples/image-03-720.webp 720w, /images/service-galleries/caramel-apples/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Карамельные яблоки — фото 3",
    },
  ],
  "roll-ice-cream": [
    {
      id: "roll-ice-cream-image-01",
      src: "/images/service-galleries/roll-ice-cream/image-01.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-01-original.png",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-01-480.webp 480w, /images/service-galleries/roll-ice-cream/image-01-720.webp 720w, /images/service-galleries/roll-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 817,
      originalWidth: 1170,
      originalHeight: 996,
      alt: "Ролл-мороженое — фото 1",
    },
    {
      id: "roll-ice-cream-image-02",
      src: "/images/service-galleries/roll-ice-cream/image-02.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-02-original.png",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-02-480.webp 480w, /images/service-galleries/roll-ice-cream/image-02-720.webp 720w, /images/service-galleries/roll-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 767,
      originalWidth: 1018,
      originalHeight: 813,
      alt: "Ролл-мороженое — фото 2",
    },
    {
      id: "roll-ice-cream-image-03",
      src: "/images/service-galleries/roll-ice-cream/image-03.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-03-480.webp 480w, /images/service-galleries/roll-ice-cream/image-03-720.webp 720w, /images/service-galleries/roll-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Ролл-мороженое — фото 3",
    },
    {
      id: "roll-ice-cream-image-04",
      src: "/images/service-galleries/roll-ice-cream/image-04.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-04-480.webp 480w, /images/service-galleries/roll-ice-cream/image-04-720.webp 720w, /images/service-galleries/roll-ice-cream/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Ролл-мороженое — фото 4",
    },
    {
      id: "roll-ice-cream-image-05",
      src: "/images/service-galleries/roll-ice-cream/image-05.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-05-480.webp 480w, /images/service-galleries/roll-ice-cream/image-05-720.webp 720w, /images/service-galleries/roll-ice-cream/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 1280,
      originalHeight: 960,
      alt: "Ролл-мороженое — фото 5",
    },
    {
      id: "roll-ice-cream-image-06",
      src: "/images/service-galleries/roll-ice-cream/image-06.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-06-480.webp 480w, /images/service-galleries/roll-ice-cream/image-06-720.webp 720w, /images/service-galleries/roll-ice-cream/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 1280,
      originalHeight: 960,
      alt: "Ролл-мороженое — фото 6",
    },
    {
      id: "roll-ice-cream-image-07",
      src: "/images/service-galleries/roll-ice-cream/image-07.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-07-original.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-07-480.webp 480w, /images/service-galleries/roll-ice-cream/image-07-720.webp 720w, /images/service-galleries/roll-ice-cream/image-07-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Ролл-мороженое — фото 7",
    },
  ],
  "scoop-ice-cream": [
    {
      id: "scoop-ice-cream-image-01",
      src: "/images/service-galleries/scoop-ice-cream/image-01.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-01-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-01-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шариковое мороженое — фото 1",
    },
    {
      id: "scoop-ice-cream-image-02",
      src: "/images/service-galleries/scoop-ice-cream/image-02.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-02-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-02-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шариковое мороженое — фото 2",
    },
    {
      id: "scoop-ice-cream-image-03",
      src: "/images/service-galleries/scoop-ice-cream/image-03.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-03-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-03-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шариковое мороженое — фото 3",
    },
    {
      id: "scoop-ice-cream-image-04",
      src: "/images/service-galleries/scoop-ice-cream/image-04.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-04-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-04-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шариковое мороженое — фото 4",
    },
    {
      id: "scoop-ice-cream-image-05",
      src: "/images/service-galleries/scoop-ice-cream/image-05.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-05-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-05-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Шариковое мороженое — фото 5",
    },
  ],
  "nitro-ice-cream": [
    {
      id: "nitro-ice-cream-image-01",
      src: "/images/service-galleries/nitro-ice-cream/image-01.jpg",
      originalSrc: "/images/service-galleries/nitro-ice-cream/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-01-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-01-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Азотное мороженое — фото 1",
    },
    {
      id: "nitro-ice-cream-image-02",
      src: "/images/service-galleries/nitro-ice-cream/image-02.jpg",
      originalSrc: "/images/service-galleries/nitro-ice-cream/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-02-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-02-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Азотное мороженое — фото 2",
    },
  ],
  "foam-cannon": [
    {
      id: "foam-cannon-image-01",
      src: "/images/service-galleries/foam-cannon/image-01.jpg",
      originalSrc: "/images/service-galleries/foam-cannon/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/foam-cannon/image-01-480.webp 480w, /images/service-galleries/foam-cannon/image-01-720.webp 720w, /images/service-galleries/foam-cannon/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 1280,
      originalHeight: 960,
      alt: "Пенная пушка — фото 1",
    },
    {
      id: "foam-cannon-image-02",
      src: "/images/service-galleries/foam-cannon/image-02.jpg",
      originalSrc: "/images/service-galleries/foam-cannon/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/foam-cannon/image-02-480.webp 480w, /images/service-galleries/foam-cannon/image-02-720.webp 720w, /images/service-galleries/foam-cannon/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 1280,
      originalHeight: 960,
      alt: "Пенная пушка — фото 2",
    },
    {
      id: "foam-cannon-image-03",
      src: "/images/service-galleries/foam-cannon/image-03.jpg",
      originalSrc: "/images/service-galleries/foam-cannon/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/foam-cannon/image-03-480.webp 480w, /images/service-galleries/foam-cannon/image-03-720.webp 720w, /images/service-galleries/foam-cannon/image-03-956.webp 956w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 956,
      height: 1276,
      originalWidth: 956,
      originalHeight: 1276,
      alt: "Пенная пушка — фото 3",
    },
    {
      id: "foam-cannon-image-04",
      src: "/images/service-galleries/foam-cannon/image-04.jpg",
      originalSrc: "/images/service-galleries/foam-cannon/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/foam-cannon/image-04-480.webp 480w, /images/service-galleries/foam-cannon/image-04-720.webp 720w, /images/service-galleries/foam-cannon/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 640,
      originalWidth: 1280,
      originalHeight: 853,
      alt: "Пенная пушка — фото 4",
    },
  ],
  "chocolate-fountain": [
    {
      id: "chocolate-fountain-image-01",
      src: "/images/service-galleries/chocolate-fountain/image-01.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-01-480.webp 480w, /images/service-galleries/chocolate-fountain/image-01-720.webp 720w, /images/service-galleries/chocolate-fountain/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1200,
      originalHeight: 1600,
      alt: "Шоколадный фонтан — фото 1",
    },
    {
      id: "chocolate-fountain-image-02",
      src: "/images/service-galleries/chocolate-fountain/image-02.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-02-480.webp 480w, /images/service-galleries/chocolate-fountain/image-02-720.webp 720w, /images/service-galleries/chocolate-fountain/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Шоколадный фонтан — фото 2",
    },
    {
      id: "chocolate-fountain-image-03",
      src: "/images/service-galleries/chocolate-fountain/image-03.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-03-480.webp 480w, /images/service-galleries/chocolate-fountain/image-03-720.webp 720w, /images/service-galleries/chocolate-fountain/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шоколадный фонтан — фото 3",
    },
    {
      id: "chocolate-fountain-image-04",
      src: "/images/service-galleries/chocolate-fountain/image-04.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-04-480.webp 480w, /images/service-galleries/chocolate-fountain/image-04-720.webp 720w, /images/service-galleries/chocolate-fountain/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шоколадный фонтан — фото 4",
    },
    {
      id: "chocolate-fountain-image-05",
      src: "/images/service-galleries/chocolate-fountain/image-05.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-05-480.webp 480w, /images/service-galleries/chocolate-fountain/image-05-720.webp 720w, /images/service-galleries/chocolate-fountain/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шоколадный фонтан — фото 5",
    },
    {
      id: "chocolate-fountain-image-06",
      src: "/images/service-galleries/chocolate-fountain/image-06.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-06-480.webp 480w, /images/service-galleries/chocolate-fountain/image-06-720.webp 720w, /images/service-galleries/chocolate-fountain/image-06-938.webp 938w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 938,
      height: 1243,
      originalWidth: 938,
      originalHeight: 1243,
      alt: "Шоколадный фонтан — фото 6",
    },
  ],
  "french-hot-dog": [
    {
      id: "french-hot-dog-image-01",
      src: "/images/service-galleries/french-hot-dog/image-01.jpg",
      originalSrc: "/images/service-galleries/french-hot-dog/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/french-hot-dog/image-01-480.webp 480w, /images/service-galleries/french-hot-dog/image-01-720.webp 720w, /images/service-galleries/french-hot-dog/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Французский хот-дог — фото 1",
    },
    {
      id: "french-hot-dog-image-02",
      src: "/images/service-galleries/french-hot-dog/image-02.jpg",
      originalSrc: "/images/service-galleries/french-hot-dog/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/french-hot-dog/image-02-480.webp 480w, /images/service-galleries/french-hot-dog/image-02-720.webp 720w, /images/service-galleries/french-hot-dog/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Французский хот-дог — фото 2",
    },
    {
      id: "french-hot-dog-image-03",
      src: "/images/service-galleries/french-hot-dog/image-03.jpg",
      originalSrc: "/images/service-galleries/french-hot-dog/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/french-hot-dog/image-03-480.webp 480w, /images/service-galleries/french-hot-dog/image-03-720.webp 720w, /images/service-galleries/french-hot-dog/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Французский хот-дог — фото 3",
    },
    {
      id: "french-hot-dog-image-04",
      src: "/images/service-galleries/french-hot-dog/image-04.jpg",
      originalSrc: "/images/service-galleries/french-hot-dog/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/french-hot-dog/image-04-480.webp 480w, /images/service-galleries/french-hot-dog/image-04-720.webp 720w, /images/service-galleries/french-hot-dog/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Французский хот-дог — фото 4",
    },
    {
      id: "french-hot-dog-image-05",
      src: "/images/service-galleries/french-hot-dog/image-05.jpg",
      originalSrc: "/images/service-galleries/french-hot-dog/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/french-hot-dog/image-05-480.webp 480w, /images/service-galleries/french-hot-dog/image-05-720.webp 720w, /images/service-galleries/french-hot-dog/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Французский хот-дог — фото 5",
    },
    {
      id: "french-hot-dog-image-06",
      src: "/images/service-galleries/french-hot-dog/image-06.jpg",
      originalSrc: "/images/service-galleries/french-hot-dog/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/french-hot-dog/image-06-480.webp 480w, /images/service-galleries/french-hot-dog/image-06-720.webp 720w, /images/service-galleries/french-hot-dog/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Французский хот-дог — фото 6",
    },
  ],
  "danish-hot-dog": [
    {
      id: "danish-hot-dog-image-01",
      src: "/images/service-galleries/danish-hot-dog/image-01.jpg",
      originalSrc: "/images/service-galleries/danish-hot-dog/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/danish-hot-dog/image-01-480.webp 480w, /images/service-galleries/danish-hot-dog/image-01-720.webp 720w, /images/service-galleries/danish-hot-dog/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Датский хот-дог — фото 1",
    },
    {
      id: "danish-hot-dog-image-02",
      src: "/images/service-galleries/danish-hot-dog/image-02.jpg",
      originalSrc: "/images/service-galleries/danish-hot-dog/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/danish-hot-dog/image-02-480.webp 480w, /images/service-galleries/danish-hot-dog/image-02-720.webp 720w, /images/service-galleries/danish-hot-dog/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Датский хот-дог — фото 2",
    },
    {
      id: "danish-hot-dog-image-03",
      src: "/images/service-galleries/danish-hot-dog/image-03.jpg",
      originalSrc: "/images/service-galleries/danish-hot-dog/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/danish-hot-dog/image-03-480.webp 480w, /images/service-galleries/danish-hot-dog/image-03-720.webp 720w, /images/service-galleries/danish-hot-dog/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Датский хот-дог — фото 3",
    },
    {
      id: "danish-hot-dog-image-04",
      src: "/images/service-galleries/danish-hot-dog/image-04.jpg",
      originalSrc: "/images/service-galleries/danish-hot-dog/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/danish-hot-dog/image-04-480.webp 480w, /images/service-galleries/danish-hot-dog/image-04-720.webp 720w, /images/service-galleries/danish-hot-dog/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Датский хот-дог — фото 4",
    },
    {
      id: "danish-hot-dog-image-05",
      src: "/images/service-galleries/danish-hot-dog/image-05.jpg",
      originalSrc: "/images/service-galleries/danish-hot-dog/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/danish-hot-dog/image-05-480.webp 480w, /images/service-galleries/danish-hot-dog/image-05-720.webp 720w, /images/service-galleries/danish-hot-dog/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Датский хот-дог — фото 5",
    },
    {
      id: "danish-hot-dog-image-06",
      src: "/images/service-galleries/danish-hot-dog/image-06.jpg",
      originalSrc: "/images/service-galleries/danish-hot-dog/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/danish-hot-dog/image-06-480.webp 480w, /images/service-galleries/danish-hot-dog/image-06-720.webp 720w, /images/service-galleries/danish-hot-dog/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Датский хот-дог — фото 6",
    },
  ],
  "burgers": [
    {
      id: "burgers-image-01",
      src: "/images/service-galleries/burgers/image-01.jpg",
      originalSrc: "/images/service-galleries/burgers/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/burgers/image-01-480.webp 480w, /images/service-galleries/burgers/image-01-720.webp 720w, /images/service-galleries/burgers/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бургеры — фото 1",
    },
    {
      id: "burgers-image-02",
      src: "/images/service-galleries/burgers/image-02.jpg",
      originalSrc: "/images/service-galleries/burgers/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/burgers/image-02-480.webp 480w, /images/service-galleries/burgers/image-02-720.webp 720w, /images/service-galleries/burgers/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 1280,
      originalHeight: 960,
      alt: "Бургеры — фото 2",
    },
    {
      id: "burgers-image-03",
      src: "/images/service-galleries/burgers/image-03.jpg",
      originalSrc: "/images/service-galleries/burgers/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/burgers/image-03-480.webp 480w, /images/service-galleries/burgers/image-03-720.webp 720w, /images/service-galleries/burgers/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1234,
      originalWidth: 996,
      originalHeight: 1280,
      alt: "Бургеры — фото 3",
    },
  ],
  "belgian-waffles": [
    {
      id: "belgian-waffles-image-01",
      src: "/images/service-galleries/belgian-waffles/image-01.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-01-480.webp 480w, /images/service-galleries/belgian-waffles/image-01-720.webp 720w, /images/service-galleries/belgian-waffles/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бельгийские вафли — фото 1",
    },
    {
      id: "belgian-waffles-image-02",
      src: "/images/service-galleries/belgian-waffles/image-02.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-02-480.webp 480w, /images/service-galleries/belgian-waffles/image-02-720.webp 720w, /images/service-galleries/belgian-waffles/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бельгийские вафли — фото 2",
    },
    {
      id: "belgian-waffles-image-03",
      src: "/images/service-galleries/belgian-waffles/image-03.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-03-480.webp 480w, /images/service-galleries/belgian-waffles/image-03-720.webp 720w, /images/service-galleries/belgian-waffles/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бельгийские вафли — фото 3",
    },
    {
      id: "belgian-waffles-image-04",
      src: "/images/service-galleries/belgian-waffles/image-04.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-04-480.webp 480w, /images/service-galleries/belgian-waffles/image-04-720.webp 720w, /images/service-galleries/belgian-waffles/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бельгийские вафли — фото 4",
    },
    {
      id: "belgian-waffles-image-05",
      src: "/images/service-galleries/belgian-waffles/image-05.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-05-480.webp 480w, /images/service-galleries/belgian-waffles/image-05-720.webp 720w, /images/service-galleries/belgian-waffles/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бельгийские вафли — фото 5",
    },
    {
      id: "belgian-waffles-image-06",
      src: "/images/service-galleries/belgian-waffles/image-06.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-06-480.webp 480w, /images/service-galleries/belgian-waffles/image-06-720.webp 720w, /images/service-galleries/belgian-waffles/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1354,
      originalWidth: 1815,
      originalHeight: 2560,
      alt: "Бельгийские вафли — фото 6",
    },
    {
      id: "belgian-waffles-image-07",
      src: "/images/service-galleries/belgian-waffles/image-07.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-07-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-07-480.webp 480w, /images/service-galleries/belgian-waffles/image-07-720.webp 720w, /images/service-galleries/belgian-waffles/image-07-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бельгийские вафли — фото 7",
    },
    {
      id: "belgian-waffles-image-08",
      src: "/images/service-galleries/belgian-waffles/image-08.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-08-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-08-480.webp 480w, /images/service-galleries/belgian-waffles/image-08-720.webp 720w, /images/service-galleries/belgian-waffles/image-08-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бельгийские вафли — фото 8",
    },
  ],
  "pancakes": [
    {
      id: "pancakes-image-01",
      src: "/images/service-galleries/pancakes/image-01.jpg",
      originalSrc: "/images/service-galleries/pancakes/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-01-480.webp 480w, /images/service-galleries/pancakes/image-01-720.webp 720w, /images/service-galleries/pancakes/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Блины — фото 1",
    },
    {
      id: "pancakes-image-02",
      src: "/images/service-galleries/pancakes/image-02.png",
      originalSrc: "/images/service-galleries/pancakes/image-02-original.png",
      webpSrcSet: "/images/service-galleries/pancakes/image-02-480.webp 480w, /images/service-galleries/pancakes/image-02-532.webp 532w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 532,
      height: 917,
      originalWidth: 532,
      originalHeight: 917,
      alt: "Блины — фото 2",
    },
    {
      id: "pancakes-image-03",
      src: "/images/service-galleries/pancakes/image-03.jpg",
      originalSrc: "/images/service-galleries/pancakes/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-03-480.webp 480w, /images/service-galleries/pancakes/image-03-720.webp 720w, /images/service-galleries/pancakes/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Блины — фото 3",
    },
  ],
  "champagne-pyramid": [
    {
      id: "champagne-pyramid-image-01",
      src: "/images/service-galleries/champagne-pyramid/image-01.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-01-480.webp 480w, /images/service-galleries/champagne-pyramid/image-01-720.webp 720w, /images/service-galleries/champagne-pyramid/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Пирамида из шампанского — фото 1",
    },
    {
      id: "champagne-pyramid-image-02",
      src: "/images/service-galleries/champagne-pyramid/image-02.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-02-480.webp 480w, /images/service-galleries/champagne-pyramid/image-02-720.webp 720w, /images/service-galleries/champagne-pyramid/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1173,
      originalWidth: 1074,
      originalHeight: 1312,
      alt: "Пирамида из шампанского — фото 2",
    },
    {
      id: "champagne-pyramid-image-03",
      src: "/images/service-galleries/champagne-pyramid/image-03.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-03-480.webp 480w, /images/service-galleries/champagne-pyramid/image-03-720.webp 720w, /images/service-galleries/champagne-pyramid/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1133,
      originalWidth: 960,
      originalHeight: 1133,
      alt: "Пирамида из шампанского — фото 3",
    },
    {
      id: "champagne-pyramid-image-04",
      src: "/images/service-galleries/champagne-pyramid/image-04.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-04-480.webp 480w, /images/service-galleries/champagne-pyramid/image-04-720.webp 720w, /images/service-galleries/champagne-pyramid/image-04-800.webp 800w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 800,
      height: 1200,
      originalWidth: 800,
      originalHeight: 1200,
      alt: "Пирамида из шампанского — фото 4",
    },
    {
      id: "champagne-pyramid-image-05",
      src: "/images/service-galleries/champagne-pyramid/image-05.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-05-480.webp 480w, /images/service-galleries/champagne-pyramid/image-05-720.webp 720w, /images/service-galleries/champagne-pyramid/image-05-853.webp 853w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 853,
      height: 1280,
      originalWidth: 853,
      originalHeight: 1280,
      alt: "Пирамида из шампанского — фото 5",
    },
  ],
  "craft-lemonade": [
    {
      id: "craft-lemonade-image-01",
      src: "/images/service-galleries/craft-lemonade/image-01.jpg",
      originalSrc: "/images/service-galleries/craft-lemonade/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/craft-lemonade/image-01-480.webp 480w, /images/service-galleries/craft-lemonade/image-01-720.webp 720w, /images/service-galleries/craft-lemonade/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Крафтовый лимонад — фото 1",
    },
    {
      id: "craft-lemonade-image-02",
      src: "/images/service-galleries/craft-lemonade/image-02.jpg",
      originalSrc: "/images/service-galleries/craft-lemonade/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/craft-lemonade/image-02-480.webp 480w, /images/service-galleries/craft-lemonade/image-02-720.webp 720w, /images/service-galleries/craft-lemonade/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 1280,
      originalHeight: 960,
      alt: "Крафтовый лимонад — фото 2",
    },
    {
      id: "craft-lemonade-image-03",
      src: "/images/service-galleries/craft-lemonade/image-03.jpg",
      originalSrc: "/images/service-galleries/craft-lemonade/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/craft-lemonade/image-03-480.webp 480w, /images/service-galleries/craft-lemonade/image-03-720.webp 720w, /images/service-galleries/craft-lemonade/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Крафтовый лимонад — фото 3",
    },
  ],
  "branded-cart": [
    {
      id: "branded-cart-image-01",
      src: "/images/service-galleries/branded-cart/image-01.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-01-480.webp 480w, /images/service-galleries/branded-cart/image-01-720.webp 720w, /images/service-galleries/branded-cart/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 1",
    },
    {
      id: "branded-cart-image-02",
      src: "/images/service-galleries/branded-cart/image-02.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-02-480.webp 480w, /images/service-galleries/branded-cart/image-02-720.webp 720w, /images/service-galleries/branded-cart/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 2",
    },
    {
      id: "branded-cart-image-03",
      src: "/images/service-galleries/branded-cart/image-03.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-03-480.webp 480w, /images/service-galleries/branded-cart/image-03-720.webp 720w, /images/service-galleries/branded-cart/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 3",
    },
    {
      id: "branded-cart-image-04",
      src: "/images/service-galleries/branded-cart/image-04.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-04-480.webp 480w, /images/service-galleries/branded-cart/image-04-720.webp 720w, /images/service-galleries/branded-cart/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Брендирование тележки для кейтеринга — фото 4",
    },
    {
      id: "branded-cart-image-05",
      src: "/images/service-galleries/branded-cart/image-05.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-05-480.webp 480w, /images/service-galleries/branded-cart/image-05-720.webp 720w, /images/service-galleries/branded-cart/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Брендирование тележки для кейтеринга — фото 5",
    },
    {
      id: "branded-cart-image-06",
      src: "/images/service-galleries/branded-cart/image-06.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-06-480.webp 480w, /images/service-galleries/branded-cart/image-06-720.webp 720w, /images/service-galleries/branded-cart/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 6",
    },
  ],
  "equipment-rental": [
    {
      id: "equipment-rental-image-01",
      src: "/images/service-galleries/equipment-rental/image-01.png",
      originalSrc: "/images/service-galleries/equipment-rental/image-01-original.png",
      webpSrcSet: "/images/service-galleries/equipment-rental/image-01-480.webp 480w, /images/service-galleries/equipment-rental/image-01-720.webp 720w, /images/service-galleries/equipment-rental/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 851,
      originalWidth: 1015,
      originalHeight: 900,
      alt: "Аренда оборудования — фото 1",
    },
    {
      id: "equipment-rental-image-02",
      src: "/images/service-galleries/equipment-rental/image-02.png",
      originalSrc: "/images/service-galleries/equipment-rental/image-02-original.png",
      webpSrcSet: "/images/service-galleries/equipment-rental/image-02-306.webp 306w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 306,
      height: 545,
      originalWidth: 306,
      originalHeight: 545,
      alt: "Аренда оборудования — фото 2",
    },
    {
      id: "equipment-rental-image-03",
      src: "/images/service-galleries/equipment-rental/image-03.png",
      originalSrc: "/images/service-galleries/equipment-rental/image-03-original.png",
      webpSrcSet: "/images/service-galleries/equipment-rental/image-03-480.webp 480w, /images/service-galleries/equipment-rental/image-03-720.webp 720w, /images/service-galleries/equipment-rental/image-03-865.webp 865w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 865,
      height: 933,
      originalWidth: 865,
      originalHeight: 933,
      alt: "Аренда оборудования — фото 3",
    },
    {
      id: "equipment-rental-image-04",
      src: "/images/service-galleries/equipment-rental/image-04.png",
      originalSrc: "/images/service-galleries/equipment-rental/image-04-original.png",
      webpSrcSet: "/images/service-galleries/equipment-rental/image-04-480.webp 480w, /images/service-galleries/equipment-rental/image-04-720.webp 720w, /images/service-galleries/equipment-rental/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 866,
      originalWidth: 986,
      originalHeight: 889,
      alt: "Аренда оборудования — фото 4",
    },
    {
      id: "equipment-rental-image-05",
      src: "/images/service-galleries/equipment-rental/image-05.jpg",
      originalSrc: "/images/service-galleries/equipment-rental/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/equipment-rental/image-05-480.webp 480w, /images/service-galleries/equipment-rental/image-05-720.webp 720w, /images/service-galleries/equipment-rental/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 481,
      originalWidth: 970,
      originalHeight: 486,
      alt: "Аренда оборудования — фото 5",
    },
  ],
  "cart-rental": [
    {
      id: "cart-rental-image-01",
      src: "/images/service-galleries/cart-rental/image-01.jpg",
      originalSrc: "/images/service-galleries/cart-rental/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/cart-rental/image-01-480.webp 480w, /images/service-galleries/cart-rental/image-01-720.webp 720w, /images/service-galleries/cart-rental/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Аренда тележек — фото 1",
    },
    {
      id: "cart-rental-image-02",
      src: "/images/service-galleries/cart-rental/image-02.jpg",
      originalSrc: "/images/service-galleries/cart-rental/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/cart-rental/image-02-480.webp 480w, /images/service-galleries/cart-rental/image-02-720.webp 720w, /images/service-galleries/cart-rental/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Аренда тележек — фото 2",
    },
    {
      id: "cart-rental-image-03",
      src: "/images/service-galleries/cart-rental/image-03.jpg",
      originalSrc: "/images/service-galleries/cart-rental/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/cart-rental/image-03-480.webp 480w, /images/service-galleries/cart-rental/image-03-720.webp 720w, /images/service-galleries/cart-rental/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Аренда тележек — фото 3",
    },
    {
      id: "cart-rental-image-04",
      src: "/images/service-galleries/cart-rental/image-04.jpg",
      originalSrc: "/images/service-galleries/cart-rental/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/cart-rental/image-04-480.webp 480w, /images/service-galleries/cart-rental/image-04-720.webp 720w, /images/service-galleries/cart-rental/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Аренда тележек — фото 4",
    },
    {
      id: "cart-rental-image-05",
      src: "/images/service-galleries/cart-rental/image-05.jpg",
      originalSrc: "/images/service-galleries/cart-rental/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/cart-rental/image-05-480.webp 480w, /images/service-galleries/cart-rental/image-05-720.webp 720w, /images/service-galleries/cart-rental/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Аренда тележек — фото 5",
    },
    {
      id: "cart-rental-image-06",
      src: "/images/service-galleries/cart-rental/image-06.jpg",
      originalSrc: "/images/service-galleries/cart-rental/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/cart-rental/image-06-480.webp 480w, /images/service-galleries/cart-rental/image-06-720.webp 720w, /images/service-galleries/cart-rental/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Аренда тележек — фото 6",
    },
  ],
  "tea-station": [
    {
      id: "tea-station-image-01",
      src: "/images/service-galleries/tea-station/image-01.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-01-480.webp 480w, /images/service-galleries/tea-station/image-01-720.webp 720w, /images/service-galleries/tea-station/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1388,
      originalWidth: 1771,
      originalHeight: 2560,
      alt: "Чайная станция — фото 1",
    },
    {
      id: "tea-station-image-02",
      src: "/images/service-galleries/tea-station/image-02.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-02-480.webp 480w, /images/service-galleries/tea-station/image-02-720.webp 720w, /images/service-galleries/tea-station/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Чайная станция — фото 2",
    },
    {
      id: "tea-station-image-03",
      src: "/images/service-galleries/tea-station/image-03.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-03-480.webp 480w, /images/service-galleries/tea-station/image-03-720.webp 720w, /images/service-galleries/tea-station/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Чайная станция — фото 3",
    },
    {
      id: "tea-station-image-04",
      src: "/images/service-galleries/tea-station/image-04.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-04-480.webp 480w, /images/service-galleries/tea-station/image-04-720.webp 720w, /images/service-galleries/tea-station/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Чайная станция — фото 4",
    },
    {
      id: "tea-station-image-05",
      src: "/images/service-galleries/tea-station/image-05.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-05-480.webp 480w, /images/service-galleries/tea-station/image-05-720.webp 720w, /images/service-galleries/tea-station/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1490,
      originalWidth: 1649,
      originalHeight: 2560,
      alt: "Чайная станция — фото 5",
    },
  ],
  "bubble-tea": [
    {
      id: "bubble-tea-image-01",
      src: "/images/service-galleries/bubble-tea/image-01.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-01-480.webp 480w, /images/service-galleries/bubble-tea/image-01-720.webp 720w, /images/service-galleries/bubble-tea/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бабл ти — фото 1",
    },
    {
      id: "bubble-tea-image-02",
      src: "/images/service-galleries/bubble-tea/image-02.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-02-480.webp 480w, /images/service-galleries/bubble-tea/image-02-720.webp 720w, /images/service-galleries/bubble-tea/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бабл ти — фото 2",
    },
    {
      id: "bubble-tea-image-03",
      src: "/images/service-galleries/bubble-tea/image-03.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-03-480.webp 480w, /images/service-galleries/bubble-tea/image-03-720.webp 720w, /images/service-galleries/bubble-tea/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бабл ти — фото 3",
    },
    {
      id: "bubble-tea-image-04",
      src: "/images/service-galleries/bubble-tea/image-04.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-04-480.webp 480w, /images/service-galleries/bubble-tea/image-04-720.webp 720w, /images/service-galleries/bubble-tea/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бабл ти — фото 4",
    },
    {
      id: "bubble-tea-image-05",
      src: "/images/service-galleries/bubble-tea/image-05.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-05-480.webp 480w, /images/service-galleries/bubble-tea/image-05-720.webp 720w, /images/service-galleries/bubble-tea/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Бабл ти — фото 5",
    },
    {
      id: "bubble-tea-image-06",
      src: "/images/service-galleries/bubble-tea/image-06.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-06-480.webp 480w, /images/service-galleries/bubble-tea/image-06-720.webp 720w, /images/service-galleries/bubble-tea/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бабл ти — фото 6",
    },
  ],
  "plov-station": [
    {
      id: "plov-station-image-01",
      src: "/images/service-galleries/plov-station/image-01.jpg",
      originalSrc: "/images/service-galleries/plov-station/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/plov-station/image-01-480.webp 480w, /images/service-galleries/plov-station/image-01-720.webp 720w, /images/service-galleries/plov-station/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Станция плова — фото 1",
    },
    {
      id: "plov-station-image-02",
      src: "/images/service-galleries/plov-station/image-02.jpg",
      originalSrc: "/images/service-galleries/plov-station/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/plov-station/image-02-480.webp 480w, /images/service-galleries/plov-station/image-02-720.webp 720w, /images/service-galleries/plov-station/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Станция плова — фото 2",
    },
  ],
};
