export type ServiceGalleryImage = {
  id: string;
  src: string;
  originalSrc: string;
  webpSrcSet: string;
  sizes: string;
  width: number;
  height: number;
  originalWidth: number;
  originalHeight: number;
  alt: string;
};

export const serviceGalleries: Partial<Record<string, ServiceGalleryImage[]>> = {
  "cotton-candy": [
    {
      id: "cotton-candy-image-01",
      src: "/images/service-galleries/cotton-candy/image-01.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-01-480.webp 480w, /images/service-galleries/cotton-candy/image-01-720.webp 720w, /images/service-galleries/cotton-candy/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Сахарная вата — фото 1",
    },
    {
      id: "cotton-candy-image-02",
      src: "/images/service-galleries/cotton-candy/image-02.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-02-480.webp 480w, /images/service-galleries/cotton-candy/image-02-720.webp 720w, /images/service-galleries/cotton-candy/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Сахарная вата — фото 2",
    },
    {
      id: "cotton-candy-image-03",
      src: "/images/service-galleries/cotton-candy/image-03.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-03-480.webp 480w, /images/service-galleries/cotton-candy/image-03-720.webp 720w, /images/service-galleries/cotton-candy/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1195,
      originalWidth: 1607,
      originalHeight: 2000,
      alt: "Сахарная вата — фото 3",
    },
    {
      id: "cotton-candy-image-04",
      src: "/images/service-galleries/cotton-candy/image-04.jpg",
      originalSrc: "/images/service-galleries/cotton-candy/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy/image-04-480.webp 480w, /images/service-galleries/cotton-candy/image-04-720.webp 720w, /images/service-galleries/cotton-candy/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 640,
      originalWidth: 1013,
      originalHeight: 675,
      alt: "Сахарная вата — фото 4",
    },
  ],
  "popcorn": [
    {
      id: "popcorn-image-01",
      src: "/images/service-galleries/popcorn/image-01.jpg",
      originalSrc: "/images/service-galleries/popcorn/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-01-480.webp 480w, /images/service-galleries/popcorn/image-01-720.webp 720w, /images/service-galleries/popcorn/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Попкорн — фото 1",
    },
    {
      id: "popcorn-image-02",
      src: "/images/service-galleries/popcorn/image-02.jpg",
      originalSrc: "/images/service-galleries/popcorn/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-02-480.webp 480w, /images/service-galleries/popcorn/image-02-720.webp 720w, /images/service-galleries/popcorn/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Попкорн — фото 2",
    },
    {
      id: "popcorn-image-03",
      src: "/images/service-galleries/popcorn/image-03.jpg",
      originalSrc: "/images/service-galleries/popcorn/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/popcorn/image-03-480.webp 480w, /images/service-galleries/popcorn/image-03-720.webp 720w, /images/service-galleries/popcorn/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Попкорн — фото 3",
    },
  ],
  "cotton-candy-popcorn": [
    {
      id: "cotton-candy-popcorn-image-01",
      src: "/images/service-galleries/cotton-candy-popcorn/image-01.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-01-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-01-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Сахарная вата + попкорн — фото 1",
    },
    {
      id: "cotton-candy-popcorn-image-02",
      src: "/images/service-galleries/cotton-candy-popcorn/image-02.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-02-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-02-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Сахарная вата + попкорн — фото 2",
    },
    {
      id: "cotton-candy-popcorn-image-03",
      src: "/images/service-galleries/cotton-candy-popcorn/image-03.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-03-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-03-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1195,
      originalWidth: 1607,
      originalHeight: 2000,
      alt: "Сахарная вата + попкорн — фото 3",
    },
    {
      id: "cotton-candy-popcorn-image-04",
      src: "/images/service-galleries/cotton-candy-popcorn/image-04.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-04-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-04-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 640,
      originalWidth: 1013,
      originalHeight: 675,
      alt: "Сахарная вата + попкорн — фото 4",
    },
    {
      id: "cotton-candy-popcorn-image-05",
      src: "/images/service-galleries/cotton-candy-popcorn/image-05.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-05-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-05-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Сахарная вата + попкорн — фото 5",
    },
    {
      id: "cotton-candy-popcorn-image-06",
      src: "/images/service-galleries/cotton-candy-popcorn/image-06.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-06-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-06-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Сахарная вата + попкорн — фото 6",
    },
    {
      id: "cotton-candy-popcorn-image-07",
      src: "/images/service-galleries/cotton-candy-popcorn/image-07.jpg",
      originalSrc: "/images/service-galleries/cotton-candy-popcorn/image-07-original.jpg",
      webpSrcSet: "/images/service-galleries/cotton-candy-popcorn/image-07-480.webp 480w, /images/service-galleries/cotton-candy-popcorn/image-07-720.webp 720w, /images/service-galleries/cotton-candy-popcorn/image-07-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Сахарная вата + попкорн — фото 7",
    },
  ],
  "caramel-apples": [
    {
      id: "caramel-apples-image-01",
      src: "/images/service-galleries/caramel-apples/image-01.jpg",
      originalSrc: "/images/service-galleries/caramel-apples/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/caramel-apples/image-01-480.webp 480w, /images/service-galleries/caramel-apples/image-01-720.webp 720w, /images/service-galleries/caramel-apples/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Карамельные яблоки — фото 1",
    },
    {
      id: "caramel-apples-image-02",
      src: "/images/service-galleries/caramel-apples/image-02.jpg",
      originalSrc: "/images/service-galleries/caramel-apples/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/caramel-apples/image-02-480.webp 480w, /images/service-galleries/caramel-apples/image-02-720.webp 720w, /images/service-galleries/caramel-apples/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Карамельные яблоки — фото 2",
    },
  ],
  "roll-ice-cream": [
    {
      id: "roll-ice-cream-image-01",
      src: "/images/service-galleries/roll-ice-cream/image-01.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-01-original.png",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-01-480.webp 480w, /images/service-galleries/roll-ice-cream/image-01-720.webp 720w, /images/service-galleries/roll-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 817,
      originalWidth: 1170,
      originalHeight: 996,
      alt: "Мороженое (Ролл) — фото 1",
    },
    {
      id: "roll-ice-cream-image-02",
      src: "/images/service-galleries/roll-ice-cream/image-02.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-02-original.png",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-02-480.webp 480w, /images/service-galleries/roll-ice-cream/image-02-720.webp 720w, /images/service-galleries/roll-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 767,
      originalWidth: 1018,
      originalHeight: 813,
      alt: "Мороженое (Ролл) — фото 2",
    },
    {
      id: "roll-ice-cream-image-03",
      src: "/images/service-galleries/roll-ice-cream/image-03.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-03-480.webp 480w, /images/service-galleries/roll-ice-cream/image-03-720.webp 720w, /images/service-galleries/roll-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Мороженое (Ролл) — фото 3",
    },
    {
      id: "roll-ice-cream-image-04",
      src: "/images/service-galleries/roll-ice-cream/image-04.jpg",
      originalSrc: "/images/service-galleries/roll-ice-cream/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/roll-ice-cream/image-04-480.webp 480w, /images/service-galleries/roll-ice-cream/image-04-720.webp 720w, /images/service-galleries/roll-ice-cream/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Мороженое (Ролл) — фото 4",
    },
  ],
  "scoop-ice-cream": [
    {
      id: "scoop-ice-cream-image-01",
      src: "/images/service-galleries/scoop-ice-cream/image-01.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-01-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-01-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Мороженое (Шариковое) — фото 1",
    },
    {
      id: "scoop-ice-cream-image-02",
      src: "/images/service-galleries/scoop-ice-cream/image-02.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-02-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-02-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Мороженое (Шариковое) — фото 2",
    },
    {
      id: "scoop-ice-cream-image-03",
      src: "/images/service-galleries/scoop-ice-cream/image-03.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-03-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-03-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Мороженое (Шариковое) — фото 3",
    },
    {
      id: "scoop-ice-cream-image-04",
      src: "/images/service-galleries/scoop-ice-cream/image-04.jpg",
      originalSrc: "/images/service-galleries/scoop-ice-cream/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/scoop-ice-cream/image-04-480.webp 480w, /images/service-galleries/scoop-ice-cream/image-04-720.webp 720w, /images/service-galleries/scoop-ice-cream/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Мороженое (Шариковое) — фото 4",
    },
  ],
  "nitro-ice-cream": [
    {
      id: "nitro-ice-cream-image-01",
      src: "/images/service-galleries/nitro-ice-cream/image-01.jpg",
      originalSrc: "/images/service-galleries/nitro-ice-cream/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-01-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-01-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Мороженое (Азотное) — фото 1",
    },
    {
      id: "nitro-ice-cream-image-02",
      src: "/images/service-galleries/nitro-ice-cream/image-02.jpg",
      originalSrc: "/images/service-galleries/nitro-ice-cream/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-02-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-02-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Мороженое (Азотное) — фото 2",
    },
    {
      id: "nitro-ice-cream-image-03",
      src: "/images/service-galleries/nitro-ice-cream/image-03.jpg",
      originalSrc: "/images/service-galleries/nitro-ice-cream/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/nitro-ice-cream/image-03-480.webp 480w, /images/service-galleries/nitro-ice-cream/image-03-720.webp 720w, /images/service-galleries/nitro-ice-cream/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Мороженое (Азотное) — фото 3",
    },
  ],
  "chocolate-fountain": [
    {
      id: "chocolate-fountain-image-01",
      src: "/images/service-galleries/chocolate-fountain/image-01.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-01-480.webp 480w, /images/service-galleries/chocolate-fountain/image-01-720.webp 720w, /images/service-galleries/chocolate-fountain/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шоколадный фонтан — фото 1",
    },
    {
      id: "chocolate-fountain-image-02",
      src: "/images/service-galleries/chocolate-fountain/image-02.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-02-480.webp 480w, /images/service-galleries/chocolate-fountain/image-02-720.webp 720w, /images/service-galleries/chocolate-fountain/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шоколадный фонтан — фото 2",
    },
    {
      id: "chocolate-fountain-image-03",
      src: "/images/service-galleries/chocolate-fountain/image-03.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-03-480.webp 480w, /images/service-galleries/chocolate-fountain/image-03-720.webp 720w, /images/service-galleries/chocolate-fountain/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1200,
      originalHeight: 1600,
      alt: "Шоколадный фонтан — фото 3",
    },
    {
      id: "chocolate-fountain-image-04",
      src: "/images/service-galleries/chocolate-fountain/image-04.jpg",
      originalSrc: "/images/service-galleries/chocolate-fountain/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/chocolate-fountain/image-04-480.webp 480w, /images/service-galleries/chocolate-fountain/image-04-720.webp 720w, /images/service-galleries/chocolate-fountain/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Шоколадный фонтан — фото 4",
    },
  ],
  "belgian-waffles": [
    {
      id: "belgian-waffles-image-01",
      src: "/images/service-galleries/belgian-waffles/image-01.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-01-480.webp 480w, /images/service-galleries/belgian-waffles/image-01-720.webp 720w, /images/service-galleries/belgian-waffles/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бельгийские вафли — фото 1",
    },
    {
      id: "belgian-waffles-image-02",
      src: "/images/service-galleries/belgian-waffles/image-02.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-02-480.webp 480w, /images/service-galleries/belgian-waffles/image-02-720.webp 720w, /images/service-galleries/belgian-waffles/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бельгийские вафли — фото 2",
    },
    {
      id: "belgian-waffles-image-03",
      src: "/images/service-galleries/belgian-waffles/image-03.jpg",
      originalSrc: "/images/service-galleries/belgian-waffles/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/belgian-waffles/image-03-480.webp 480w, /images/service-galleries/belgian-waffles/image-03-720.webp 720w, /images/service-galleries/belgian-waffles/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бельгийские вафли — фото 3",
    },
  ],
  "pancakes": [
    {
      id: "pancakes-image-01",
      src: "/images/service-galleries/pancakes/image-01.jpg",
      originalSrc: "/images/service-galleries/pancakes/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-01-480.webp 480w, /images/service-galleries/pancakes/image-01-720.webp 720w, /images/service-galleries/pancakes/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Блины — фото 1",
    },
    {
      id: "pancakes-image-02",
      src: "/images/service-galleries/pancakes/image-02.jpg",
      originalSrc: "/images/service-galleries/pancakes/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-02-480.webp 480w, /images/service-galleries/pancakes/image-02-720.webp 720w, /images/service-galleries/pancakes/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 720,
      originalWidth: 2560,
      originalHeight: 1920,
      alt: "Блины — фото 2",
    },
    {
      id: "pancakes-image-03",
      src: "/images/service-galleries/pancakes/image-03.jpg",
      originalSrc: "/images/service-galleries/pancakes/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/pancakes/image-03-480.webp 480w, /images/service-galleries/pancakes/image-03-720.webp 720w, /images/service-galleries/pancakes/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Блины — фото 3",
    },
  ],
  "champagne-pyramid": [
    {
      id: "champagne-pyramid-image-01",
      src: "/images/service-galleries/champagne-pyramid/image-01.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-01-480.webp 480w, /images/service-galleries/champagne-pyramid/image-01-720.webp 720w, /images/service-galleries/champagne-pyramid/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Пирамида из шампанского — фото 1",
    },
    {
      id: "champagne-pyramid-image-02",
      src: "/images/service-galleries/champagne-pyramid/image-02.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-02-480.webp 480w, /images/service-galleries/champagne-pyramid/image-02-720.webp 720w, /images/service-galleries/champagne-pyramid/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1173,
      originalWidth: 1074,
      originalHeight: 1312,
      alt: "Пирамида из шампанского — фото 2",
    },
    {
      id: "champagne-pyramid-image-03",
      src: "/images/service-galleries/champagne-pyramid/image-03.jpg",
      originalSrc: "/images/service-galleries/champagne-pyramid/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/champagne-pyramid/image-03-480.webp 480w, /images/service-galleries/champagne-pyramid/image-03-720.webp 720w, /images/service-galleries/champagne-pyramid/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1133,
      originalWidth: 960,
      originalHeight: 1133,
      alt: "Пирамида из шампанского — фото 3",
    },
  ],
  "craft-lemonade": [
    {
      id: "craft-lemonade-image-01",
      src: "/images/service-galleries/craft-lemonade/image-01.jpg",
      originalSrc: "/images/service-galleries/craft-lemonade/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/craft-lemonade/image-01-480.webp 480w, /images/service-galleries/craft-lemonade/image-01-720.webp 720w, /images/service-galleries/craft-lemonade/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Крафтовый лимонад — фото 1",
    },
  ],
  "branded-cart": [
    {
      id: "branded-cart-image-01",
      src: "/images/service-galleries/branded-cart/image-01.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-01-480.webp 480w, /images/service-galleries/branded-cart/image-01-720.webp 720w, /images/service-galleries/branded-cart/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 1",
    },
    {
      id: "branded-cart-image-02",
      src: "/images/service-galleries/branded-cart/image-02.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-02-480.webp 480w, /images/service-galleries/branded-cart/image-02-720.webp 720w, /images/service-galleries/branded-cart/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 2",
    },
    {
      id: "branded-cart-image-03",
      src: "/images/service-galleries/branded-cart/image-03.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-03-480.webp 480w, /images/service-galleries/branded-cart/image-03-720.webp 720w, /images/service-galleries/branded-cart/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 3",
    },
    {
      id: "branded-cart-image-04",
      src: "/images/service-galleries/branded-cart/image-04.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-04-480.webp 480w, /images/service-galleries/branded-cart/image-04-720.webp 720w, /images/service-galleries/branded-cart/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Брендирование тележки для кейтеринга — фото 4",
    },
    {
      id: "branded-cart-image-05",
      src: "/images/service-galleries/branded-cart/image-05.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-05-480.webp 480w, /images/service-galleries/branded-cart/image-05-720.webp 720w, /images/service-galleries/branded-cart/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 960,
      originalHeight: 1280,
      alt: "Брендирование тележки для кейтеринга — фото 5",
    },
    {
      id: "branded-cart-image-06",
      src: "/images/service-galleries/branded-cart/image-06.jpg",
      originalSrc: "/images/service-galleries/branded-cart/image-06-original.jpg",
      webpSrcSet: "/images/service-galleries/branded-cart/image-06-480.webp 480w, /images/service-galleries/branded-cart/image-06-720.webp 720w, /images/service-galleries/branded-cart/image-06-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Брендирование тележки для кейтеринга — фото 6",
    },
  ],
  "tea-station": [
    {
      id: "tea-station-image-01",
      src: "/images/service-galleries/tea-station/image-01.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-01-480.webp 480w, /images/service-galleries/tea-station/image-01-720.webp 720w, /images/service-galleries/tea-station/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1388,
      originalWidth: 1771,
      originalHeight: 2560,
      alt: "Чайная станция — фото 1",
    },
    {
      id: "tea-station-image-02",
      src: "/images/service-galleries/tea-station/image-02.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-02-480.webp 480w, /images/service-galleries/tea-station/image-02-720.webp 720w, /images/service-galleries/tea-station/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Чайная станция — фото 2",
    },
    {
      id: "tea-station-image-03",
      src: "/images/service-galleries/tea-station/image-03.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-03-480.webp 480w, /images/service-galleries/tea-station/image-03-720.webp 720w, /images/service-galleries/tea-station/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Чайная станция — фото 3",
    },
    {
      id: "tea-station-image-04",
      src: "/images/service-galleries/tea-station/image-04.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-04-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-04-480.webp 480w, /images/service-galleries/tea-station/image-04-720.webp 720w, /images/service-galleries/tea-station/image-04-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Чайная станция — фото 4",
    },
    {
      id: "tea-station-image-05",
      src: "/images/service-galleries/tea-station/image-05.jpg",
      originalSrc: "/images/service-galleries/tea-station/image-05-original.jpg",
      webpSrcSet: "/images/service-galleries/tea-station/image-05-480.webp 480w, /images/service-galleries/tea-station/image-05-720.webp 720w, /images/service-galleries/tea-station/image-05-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1490,
      originalWidth: 1649,
      originalHeight: 2560,
      alt: "Чайная станция — фото 5",
    },
  ],
  "bubble-tea": [
    {
      id: "bubble-tea-image-01",
      src: "/images/service-galleries/bubble-tea/image-01.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-01-480.webp 480w, /images/service-galleries/bubble-tea/image-01-720.webp 720w, /images/service-galleries/bubble-tea/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бабл ти — фото 1",
    },
    {
      id: "bubble-tea-image-02",
      src: "/images/service-galleries/bubble-tea/image-02.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-02-480.webp 480w, /images/service-galleries/bubble-tea/image-02-720.webp 720w, /images/service-galleries/bubble-tea/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бабл ти — фото 2",
    },
    {
      id: "bubble-tea-image-03",
      src: "/images/service-galleries/bubble-tea/image-03.jpg",
      originalSrc: "/images/service-galleries/bubble-tea/image-03-original.jpg",
      webpSrcSet: "/images/service-galleries/bubble-tea/image-03-480.webp 480w, /images/service-galleries/bubble-tea/image-03-720.webp 720w, /images/service-galleries/bubble-tea/image-03-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Бабл ти — фото 3",
    },
  ],
  "plov-station": [
    {
      id: "plov-station-image-01",
      src: "/images/service-galleries/plov-station/image-01.jpg",
      originalSrc: "/images/service-galleries/plov-station/image-01-original.jpg",
      webpSrcSet: "/images/service-galleries/plov-station/image-01-480.webp 480w, /images/service-galleries/plov-station/image-01-720.webp 720w, /images/service-galleries/plov-station/image-01-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Станция плова — фото 1",
    },
    {
      id: "plov-station-image-02",
      src: "/images/service-galleries/plov-station/image-02.jpg",
      originalSrc: "/images/service-galleries/plov-station/image-02-original.jpg",
      webpSrcSet: "/images/service-galleries/plov-station/image-02-480.webp 480w, /images/service-galleries/plov-station/image-02-720.webp 720w, /images/service-galleries/plov-station/image-02-960.webp 960w",
      sizes: "(max-width: 720px) 74vw, (max-width: 1120px) 34vw, 18rem",
      width: 960,
      height: 1280,
      originalWidth: 1920,
      originalHeight: 2560,
      alt: "Станция плова — фото 2",
    },
  ],
};
